export const fjender = [
  {
    navn: "Goblin Viking",
    level: 1,
    liv: 20,
    maxLiv: 20,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/Goblin.png",
    charImgDmg: "./Billeder/Goblin_damage.png",
    fjendeImgSize: "35%",
    heltImgSize: "70%",
    kanHeal: false,
    skadeModifierFjende: 0,
    minSkadeModifierFjende: 0,
    mpCostFjende: 0,
    antalExp: 20,
  },

  {
    navn: "Goblin Spellcaster",
    level: 1,
    liv: 40,
    maxLiv: 40,
    mana: 10,
    maxMana: 10,
    charImg: "./Billeder/Goblin_spell_caster.png",
    charImgDmg: "./Billeder/Goblin_spell_caster_damage.png",
    charImgHeal: "./Billeder/Goblin_spell_caster_heal.png",
    fjendeImgSize: "40%",
    heltImgSize: "70%",
    kanHeal: true,
    skadeModifierFjende: 0,
    minSkadeModifierFjende: 0,
    healModifierFjende: 5,
    minHealModifierFjende: 0,
    mpCostFjende: 0,
    antalExp: 30,
  },

  {
    navn: "Goblin Sorcerer",
    level: 1,
    liv: 70,
    maxLiv: 70,
    mana: 15,
    maxMana: 15,
    charImg: "./Billeder/Goblin_sorcerer.png",
    charImgDmg: "./Billeder/Goblin_sorcerer_damage.png",
    charImgHeal: "./Billeder/Goblin_sorcerer_heal.png",
    fjendeImgSize: "40%",
    heltImgSize: "70%",
    kanHeal: true,
    skadeModifierFjende: 0,
    minSkadeModifierFjende: 0,
    healModifierFjende: 5,
    minHealModifierFjende: 5,
    mpCostFjende: 2,
    antalExp: 40,
  },

  {
    navn: "Goblin Warrior",
    level: 1,
    liv: 100,
    maxLiv: 100,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/Goblin_warrior.png",
    charImgDmg: "./Billeder/Goblin_Warrior_damaged.png",
    fjendeImgSize: "45%",
    heltImgSize: "70%",
    kanHeal: false,
    skadeModifierFjende: 0,
    minSkadeModifierFjende: 0,
    antalExp: 140,
  },

  {
    navn: "Tent",
    level: 1,
    liv: 0,
    maxLiv: 0,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/tent.png",
    fjendeImgSize: "70%",
    heltImgSize: "70%",
    erTelt: true,
  },

  {
    navn: "Orc Warrior",
    level: 1,
    liv: 170,
    maxLiv: 170,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/Orc_warrior.png",
    charImgDmg: "./Billeder/Orc_warrior_damage.png",
    fjendeImgSize: "95%",
    heltImgSize: "70%",
    kanHeal: false,
    skadeModifierFjende: 10,
    minSkadeModifierFjende: 5,
    antalExp: 70,
  },

  {
    navn: "Orc Shaman",
    level: 1,
    liv: 200,
    maxLiv: 200,
    mana: 40,
    maxMana: 40,
    charImg: "./Billeder/Orc_shaman.png",
    charImgDmg: "./Billeder/Orc_shaman_damaged.png",
    charImgHeal: "./Billeder/Orc_shaman_heal.png",
    fjendeImgSize: "85%",
    heltImgSize: "70%",
    kanHeal: true,
    skadeModifierFjende: 10,
    minSkadeModifierFjende: 5,
    healModifierFjende: 20,
    minHealModifierFjende: 10,
    mpCostFjende: 3,
    antalExp: 100,
  },

  {
    navn: "Treasure Chest",
    level: 1,
    liv: 0,
    maxLiv: 0,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/treasure_chest_closed.png",
    fjendeImgSize: "70%",
    heltImgSize: "70%",
    erSkattekiste: true,
  },

  {
    navn: "Orc Cheif Warrior",
    level: 1,
    liv: 250,
    maxLiv: 250,
    charImg: "./Billeder/Orc_cheif_warrior.png",
    charImgDmg: "./Billeder/Orc_cheif_warrior_damage.png",
    fjendeImgSize: "85%",
    heltImgSize: "70%",
    kanHeal: false,
    skadeModifierFjende: 15,
    minSkadeModifierFjende: 10,

    antalExp: 150,
  },
  {
    navn: "Tent",
    liv: 0,
    maxLiv: 0,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/tent.png",
    fjendeImgSize: "70%",
    heltImgSize: "70%",
    erTelt: true,
  },

  {
    navn: "Skeleton sword Warrior",
    level: 1,
    liv: 60,
    maxLiv: 60,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder//skeleton_sword_warrior.png",
    charImgDmg: "./Billeder/skeleton_sword_warrior_damage.png",
    fjendeImgSize: "60%",
    heltImgSize: "70%",
    kanHeal: false,
    skadeModifierFjende: 10,
    minSkadeModifierFjende: 5,
    antalExp: 70,
  },

  {
    navn: "Skeleton Axe Warrior",
    level: 1,
    liv: 80,
    maxLiv: 60,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/skeleton_axe_warrior.png",
    charImgDmg: "./Billeder/skeleton_axe_warrior_damage.png",
    fjendeImgSize: "85%",
    heltImgSize: "70%",
    kanHeal: false,
    skadeModifierFjende: 10,
    minSkadeModifierFjende: 5,
    antalExp: 70,
  },

  {
    navn: "Skeleton Spear Warrior",
    level: 1,
    liv: 120,
    maxLiv: 60,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/skeleton_spear_warrior.png",
    charImgDmg: "./Billeder/skeleton_spear_warrior_damage.png",
    fjendeImgSize: "75%",
    heltImgSize: "70%",
    kanHeal: false,
    skadeModifierFjende: 10,
    minSkadeModifierFjende: 5,
    antalExp: 80,
  },

  {
    navn: "Dark Slime",
    level: 1,
    liv: 70,
    maxLiv: 70,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/Dark-slime.png",
    charImgDmg: "./Billeder/Dark-slime_damage.png",
    fjendeImgSize: "40%",
    heltImgSize: "70%",
    kanHeal: false,
    skadeModifierFjende: 10,
    minSkadeModifierFjende: 0,
    antalExp: 80,
  },

  {
    navn: "Ghost-Wisp",
    level: 1,
    liv: 150,
    maxLiv: 150,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/Ghost-wisp.png",
    charImgDmg: "./Billeder/Ghost-wisp_damage.png",
    fjendeImgSize: "40%",
    heltImgSize: "70%",
    kanHeal: false,
    skadeModifierFjende: 15,
    minSkadeModifierFjende: 0,
    antalExp: 90,
  },

  {
    navn: "Undead Warrior",
    level: 1,
    liv: 170,
    maxLiv: 170,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder//Undead-warrior.png",
    charImgDmg: "./Billeder/Undead-warrior_damage.png",
    fjendeImgSize: "65%",
    heltImgSize: "70%",
    kanHeal: false,
    skadeModifierFjende: 30,
    minSkadeModifierFjende: 0,
    antalExp: 90,
  },

  {
    navn: "Dark Sorcerer",
    level: 1,
    liv: 200,
    maxLiv: 200,
    mana: 40,
    maxMana: 40,
    charImg: "./Billeder/dark_sorcerer.png",
    charImgDmg: "./Billeder/dark_sorcerer_damage.png",
    charImgHeal: "./Billeder/dark_sorcerer_heal.png",
    fjendeImgSize: "90%",
    heltImgSize: "70%",
    kanHeal: true,
    skadeModifierFjende: 30,
    minSkadeModifierFjende: 0,
    healModifierFjende: 35,
    minHealModifierFjende: 5,
    antalExp: 120,
  },
  {
    navn: "Treasure Chest",
    level: 1,
    liv: 0,
    maxLiv: 0,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/treasure_chest_closed.png",
    fjendeImgSize: "70%",
    heltImgSize: "70%",
    erSkattekiste: true,
  },
  {
    navn: "Tent",
    liv: 0,
    maxLiv: 0,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/tent.png",
    fjendeImgSize: "70%",
    heltImgSize: "70%",
    erTelt: true,
  },

  {
    navn: "Void Spawn",
    level: 1,
    liv: 280,
    maxLiv: 280,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/Voidspawn.png",
    charImgDmg: "./Billeder/Voidspawn_damage.png",
    fjendeImgSize: "90%",
    heltImgSize: "70%",
    kanHeal: false,
    skadeModifierFjende: 30,
    minSkadeModifierFjende: 5,
    antalExp: 160,
  },

  {
    navn: "Cragjaw",
    level: 1,
    liv: 300,
    maxLiv: 300,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/Cragjaw.png",
    charImgDmg: "./Billeder/Cragjaw_damage.png",
    fjendeImgSize: "110%",
    heltImgSize: "70%",
    kanHeal: false,
    skadeModifierFjende: 40,
    minSkadeModifierFjende: 10,

    antalExp: 200,
  },

  {
    navn: "whispering Wood Feind",
    level: 1,
    liv: 350,
    maxLiv: 350,
    mana: 80,
    maxMana: 80,
    charImg: "./Billeder/Whispering-wood-feind.png",
    charImgDmg: "./Billeder/Whispering-wood-feind_damage.png",
    charImgHeal: "./Billeder/Whispering-wood-feind_heal.png",
    fjendeImgSize: "80%",
    heltImgSize: "70%",
    kanHeal: true,
    skadeModifierFjende: 45,
    minSkadeModifierFjende: 10,
    healModifierFjende: 40,
    minHealModifierFjende: 20,
    antalExp: 2400,
  },
  {
    navn: "Tent",
    liv: 0,
    maxLiv: 0,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/tent.png",
    fjendeImgSize: "70%",
    heltImgSize: "70%",
    erTelt: true,
  },
  {
    navn: "Treasure Chest",
    level: 1,
    liv: 0,
    maxLiv: 0,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/treasure_chest_closed.png",
    fjendeImgSize: "70%",
    heltImgSize: "70%",
    erSkattekiste: true,
  },

  {
    navn: "Dragon Child",
    level: 1,
    liv: 370,
    maxLiv: 370,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/dragon_child.png",
    charImgDmg: "./Billeder/dragon_child_damage.png",
    fjendeImgSize: "75%",
    heltImgSize: "70%",
    kanHeal: false,
    skadeModifierFjende: 40,
    minSkadeModifierFjende: 20,
    antalExp: 270,
  },

  {
    navn: "Dragon Guard",
    level: 1,
    liv: 380,
    maxLiv: 380,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/dragon_guard.png",
    charImgDmg: "./Billeder/dragon_guard_damage.png",
    fjendeImgSize: "80%",
    heltImgSize: "70%",
    kanHeal: false,
    skadeModifierFjende: 40,
    minSkadeModifierFjende: 20,
    antalExp: 300,
  },

  {
    navn: "Viquix",
    level: 1,
    liv: 450,
    maxLiv: 450,
    mana: 90,
    maxMana: 90,
    charImg: "./Billeder/Viquix.png",
    charImgDmg: "./Billeder/Viquix_damage.png",
    charImgHeal: "./Billeder/Viquix_heal.png",
    fjendeImgSize: "90%",
    heltImgSize: "50%",
    kanHeal: true,
    skadeModifierFjende: 50,
    minSkadeModifierFjende: 30,
    healModifierFjende: 40,
    minHealModifierFjende: 20,
    antalExp: 350,
  },

  {
    navn: "Fenrir",
    level: 1,
    liv: 600,
    maxLiv: 600,
    mana: 100,
    maxMana: 100,
    charImg: "./Billeder/Fenrir.png",
    charImgDmg: "./Billeder/Fenrir_damage.png",
    charImgHeal: "./Billeder/Fenrir_heal.png",
    fjendeImgSize: "85%",
    heltImgSize: "45%",
    kanHeal: true,
    skadeModifierFjende: 50,
    minSkadeModifierFjende: 30,
    healModifierFjende: 40,
    minHealModifierFjende: 25,
    antalExp: 400,
  },
  {
    navn: "Treasure Chest",
    level: 1,
    liv: 0,
    maxLiv: 0,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/treasure_chest_closed.png",
    fjendeImgSize: "70%",
    heltImgSize: "70%",
    erSkattekiste: true,
  },

  {
    navn: "Wyrith",
    level: 1,
    liv: 100,
    maxLiv: 100,
    mana: 150,
    maxMana: 150,
    charImg: "./Billeder/Wyrith.png",
    charImgDmg: "./Billeder/Wyrith_damage.png",
    charImgHeal: "./Billeder/Wyrith_heal.png",
    fjendeImgSize: "90%",
    heltImgSize: "40%",
    kanHeal: true,
    skadeModifierFjende: 60,
    minSkadeModifierFjende: 40,
    healModifierFjende: 70,
    minHealModifierFjende: 30,
    antalExp: 0,
  },
];

export const skatteKister = [
  {
    navn: "Treasure Chest",
    level: 1,
    liv: 0,
    maxLiv: 0,
    mana: 0,
    maxMana: 0,
    skattekisteVaaben: "Hero_Silver_Sword.png",
    treasure: "treasure_chest_open_white_silver_sword.png",
    fjendeImgSize: "70%",
    heltImgSize: "70%",
    erSkattekiste: true,
    maxHPIncreaseHelt: 20,
    skadeModifierHelt: 10,
    healModifierHelt: 10,
    minSkadeModifierHelt: 5,
    spcSkadeModifierHelt: 10,
    MinspcSkadeModifierHelt: 5,
  },
  {
    navn: "Treasure Chest",
    level: 1,
    liv: 0,
    maxLiv: 0,
    mana: 0,
    maxMana: 0,
    skattekisteVaaben: "Hero_Kings_Sword.png",
    treasure: "treasure_chest_open_kings_sword.png",
    fjendeImgSize: "70%",
    heltImgSize: "70%",
    erSkattekiste: true,
    maxHPIncreaseHelt: 30,
    skadeModifierHelt: 10,
    minSkadeModifierHelt: 5,
    spcSkadeModifierHelt: 20,
    MinspcSkadeModifierHelt: 10,
  },
  {
    navn: "Treasure Chest",
    level: 1,
    liv: 0,
    maxLiv: 0,
    mana: 0,
    maxMana: 0,
    skattekisteVaaben: "Hero_Dragon_Sword.png",
    treasure: "treasure_chest_open_dragon_sword.png",
    fjendeImgSize: "70%",
    heltImgSize: "70%",
    erSkattekiste: true,
    maxHPIncreaseHelt: 40,
    skadeModifierHelt: 40,
    minSkadeModifierHelt: 20,
    spcSkadeModifierHelt: 50,
    MinspcSkadeModifierHelt: 25,
  },
];

export const mimics = [
  {
    navn: "Mimic",
    level: 3,
    liv: 100,
    maxLiv: 100,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/Mimic.png",
    charImgDmg: "./Billeder/mimic_damage.png",
    fjendeImgSize: "70%",
    heltImgSize: "70%",
    kanHeal: false,
    erMimic: true,
    skadeModifierFjende: 10,
    minSkadeModifierFjende: 0,
    antalExp: 50,
  },
  {
    navn: "Mimic",
    level: 5,
    liv: 175,
    maxLiv: 175,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/Mimic.png",
    charImgDmg: "./Billeder/mimic_damage.png",
    fjendeImgSize: "70%",
    heltImgSize: "70%",
    kanHeal: false,
    erMimic: true,
    skadeModifierFjende: 20,
    minSkadeModifierFjende: 5,
    antalExp: 80,
  },
  {
    navn: "Mimic",
    level: 7,
    liv: 250,
    maxLiv: 250,
    mana: 0,
    maxMana: 0,
    charImg: "./Billeder/Mimic.png",
    charImgDmg: "./Billeder/mimic_damage.png",
    fjendeImgSize: "70%",
    heltImgSize: "70%",
    kanHeal: false,
    erMimic: true,
    skadeModifierFjende: 30,
    minSkadeModifierFjende: 10,
    antalExp: 150,
  },
];

export const fjendeVariabler = {
  fjendeNavn: document.getElementById("fjendeNavn"),
  fjendeLevel: document.getElementById("fjendeLevel"),
  fjendeLiv: document.getElementById("HPfjende"),
  fjendeLivMax: document.getElementById("MaxHPfjende"),
  fjendeMana: document.getElementById("mpfjende"),
  fjendeManaMax: document.getElementById("maxMPFjende"),
  fjendeCharImg: document.getElementById("fjendeCharImg"),
  hpFillBarFjende: document.getElementById("hpFillFjende"),
  manaFillBarFjende: document.getElementById("manaFillFjende"),
  nuvaerendeFjendeIndex: 0,
  nuvaerendeFjende: fjender[0],
};
