export let levels = [
  {
    level: 1,
    skadeModifier: 0,
    minSkadeModifier: 0,
    spcSkademodifier: 0,
    minSpecSkadeModifier: 0,
    spcAttackMpCostIncrease: 0,
    healModifier: 0,
    minHealModifier: 0,
    maxHPIncrease: 0,
    maxMPIncrease: 0,
    mpCostIncrease: 0,
  },
  {
    level: 2,
    skadeModifier: 10,
    minSkadeModifier: 0,
    spcSkademodifier: 5,
    minSpecSkadeModifier: 0,
    spcAttackMpCostIncrease: 2,
    healModifier: 5,
    minHealModifier: 0,
    maxHPIncrease: 15,
    maxMPIncrease: 5,
    mpCostIncrease: 0,
  },
  {
    level: 3,
    skadeModifier: 0,
    minSkadeModifier: 5,
    spcSkademodifier: 5,
    minSpecSkadeModifier: 0,
    spcAttackMpCostIncrease: 3,
    healModifier: 10,
    maxHPIncrease: 5,
    maxMPIncrease: 10,
  },
  {
    level: 4,
    skadeModifier: 5,
    minSkadeModifier: 5,
    spcSkademodifier: 5,
    minSpecSkadeModifier: 5,
    spcAttackMpCostIncrease: 0,
    healModifier: 5,
    maxHPIncrease: 10,
    maxMPIncrease: 5,
  },
  {
    level: 5,
    skadeModifier: 5,
    minSkadeModifier: 0,
    spcSkademodifier: 0,
    minSpecSkadeModifier: 5,
    spcAttackMpCostIncrease: 5,
    healModifier: 5,
    maxHPIncrease: 15,
    maxMPIncrease: 10,
  },
  {
    level: 6,
    skadeModifier: 10,
    minSkadeModifier: 5,
    spcSkademodifier: 5,
    minSpecSkadeModifier: 5,
    spcAttackMpCostIncrease: 3,
    healModifier: 10,
    maxHPIncrease: 15,
    maxMPIncrease: 15,
  },
  {
    level: 7,
    skadeModifier: 5,
    minSkadeModifier: 0,
    spcSkademodifier: 5,
    minSpecSkadeModifier: 0,
    spcAttackMpCostIncrease: 2,
    healModifier: 10,
    maxHPIncrease: 15,
    maxMPIncrease: 5,
  },
  {
    level: 8,
    skadeModifier: 10,
    minSkadeModifer: 0,
    spcSkademodifier: 5,
    minSpecSkadeModifier: 0,
    spcAttackMpCostIncrease: 4,
    healModifier: 5,
    maxHPIncrease: 10,
    maxMPIncrease: 10,
  },
  {
    level: 9,
    skadeModifier: 10,
    minSkadeModifer: 5,
    spcSkademodifier: 5,
    minSpecSkadeModifier: 5,
    spcAttackMpCostIncrease: 3,
    healModifier: 10,
    maxHPIncrease: 15,
    maxMPIncrease: 5,
  },
  {
    level: 10,
    skadeModifier: 0,
    minSkadeModifer: 5,
    spcSkademodifier: 0,
    minSpecSkadeModifier: 5,
    spcAttackMpCostIncrease: 3,
    healModifier: 10,
    maxHPIncrease: 10,
    maxMPIncrease: 5,
  },
  {
    level: 11,
    skadeModifier: 5,
    minSkadeModifer: 5,
    spcSkademodifier: 5,
    minSpecSkadeModifier: 5,
    spcAttackMpCostIncrease: 0,
    healModifier: 5,
    maxHPIncrease: 10,
    maxMPIncrease: 5,
  },
  {
    level: 12,
    skadeModifier: 10,
    minSkadeModifer: 5,
    spcSkademodifier: 10,
    minSpecSkadeModifier: 5,
    spcAttackMpCostIncrease: 0,
    healModifier: 10,
    maxHPIncrease: 10,
    maxMPIncrease: 5,
  },
  {
    level: 13,
    skadeModifier: 5,
    minSkadeModifer: 0,
    spcSkademodifier: 5,
    minSpecSkadeModifier: 0,
    spcAttackMpCostIncrease: 0,
    healModifier: 5,
    maxHPIncrease: 5,
    maxMPIncrease: 10,
  },
  {
    level: 14,
    skadeModifier: 5,
    minSkadeModifer: 5,
    spcSkademodifier: 5,
    minSpecSkadeModifier: 5,
    spcAttackMpCostIncrease: 0,
    healModifier: 5,
    maxHPIncrease: 10,
    maxMPIncrease: 5,
  },
  {
    level: 15,
    skadeModifier: 10,
    minSkadeModifer: 15,
    spcSkademodifier: 10,
    minSpecSkadeModifier: 15,
    spcAttackMpCostIncrease: 5,
    healModifier: 10,
    maxHPIncrease: 10,
    maxMPIncrease: 15,
  },
];
